### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by ginty**
This is a major overhaul of the V93K lib and a breaking change, it includes the following:

* Incorporates learning from using this in its first production deployment
* Improves the architecture to enable closer integration with the Origen test program generator
* Drops support for limits attached directly to test suites and moves to a testtable limits file
* Consolidates and simplifies the callback naming and conventions
* Enables 'green box' flow control

Here is an overview of how it works, this will be converted to formal documentation later:

### Integration

The lib continues to provide a number of complete off-the-shelf test methods, currently a functional test, DC measurement and frequency measurement.
These are unchanged vs. the existing release except to add a few additional arguments which are common to all tests and which will be discussed below.

To use the lib to create a custom test method, the test method class should inherit from one of the base classes provided in `origen/test_method` instead of the `testmethod::TestMethod` base class provided by SMT7.
An empty class has been added to enable integration with test methods which are very customized and which do not align well to one of the other base classes.

For example, to create a custom test method based on a functional test:

~~~cpp
#include "origen/test_method/functional_test.hpp"

class MyTest: public Origen::TestMethod::FunctionalTest {


};
REGISTER_TESTMETHOD("MyTest", MyTest);
~~~

or to create a custom test with minimal support from the std lib:

~~~cpp
#include "origen/test_method/empty.hpp"

class MyTest: public Origen::TestMethod::Empty {


};
REGISTER_TESTMETHOD("MyTest", MyTest);
~~~

Every test method that inherits from one of the Origen base classes will have the following arguments:

* **testName** - Allows the name given to the test suite to be overridden for the purposes of datalogging. Test method code should use the `testName()` function to retrieve the test name, which will return the value given to this argument if supplied, otherwise falling back to the name of the test suite.
* **forcePass** - When set to 1, the test limits will be forced to N/A so that the test will always pass.
* **onPassFlag** - The name of a flow control flag to be set if the test passes.
* **onFailFlag** - The name of a flow control flag to be set if the test fails. Note that setting `forcePass` will not mean that this is never hit, the internal pass/fail status used to set these flags will be evaluated based on the original limits before `forcePass` is applied to set the overall test pass/fail state.

These arguments will be filled in by the Origen test program generator, therefore it is recommended that **every test which is generated via Origen should always use a test method that inherits from an Origen test method class.**
However, this is not mandatory but will be required to use some features provided by the program generator.

This list may be expanded in future to enable further feature integration with the Origen program generator, though there are no such plans at present.

### Function Naming and Callbacks

When using an Origen test method (as opposed to a standard SMT7 test method), **the following rules should be strictly adhered to**:

* Implement a function called `init()` instead of `initialize()` to add additional arguments
* Implement the test in a function called `body()` instead of `run()`

Here is an example of how it should look:
~~~cpp
#include "origen/test_method/functional_test.hpp"

class MyTest: public Origen::TestMethod::FunctionalTest {
   /**
    *Initialize the parameter interface to the testflow.
    *This method is called just once after a testsuite is created.
    */
    void init() {
        //Add your initialization code here
        //Note: Test Method API should not be used in this method!
	addParameter("events",
                     "int",
                     &mEvents,
                     testmethod::TM_PARAMETER_INPUT)
	  .setDefault("1")
	  .setComment("The number of events in the pattern");        
    }

   /**
    *This test is invoked per site.
    */
   void body() {
       // Your test code here
   }

};
REGISTER_TESTMETHOD("MyTest", MyTest);
~~~

The following callback handlers can be implemented as required:

* **void preBody()** - Called before body() on first invocation
* **void preBody(int site)** - Called before body() on each site, the current site number is passed in
* **void filterRDI(\<RDI type\>)** - Test method base classes which implement a single/central RDI-based operation will invoke this callback immediately before executing it. This gives the parent test method a chance to augment or change some of the base settings used by it.
* **void holdState()** - Test method base classes which have the concept of a hold state (e.g. the DC measurement), will call this on first invocation once the setup pattern has been run and before the measurement is take.
* **void holdState(int site)** - As above, but called on every site individually.
* **void postBody()** - Called after body() on first invocation
* **void postBody(int site)** Called after body() on each site, the current site number is passed in
* **void process(int site)** - Called after postBody(), this is similar but with the subtle difference that if the test method supports asynchronous processing (none do at present), then this will be called during the background process. If async is not enabled then it is effectively the same as postBody().
* **double filterResult(double result)** - Test base classes which have the concept of a single parametric result, will call this method after generating the result but before evaluating it against the limits, thus giving the parent test method a chance to transform it.

### Binning and Logging

Here are some examples of how to log and bin on results, this will pick up limits, test numbers, etc. from the current test table:

~~~cpp
double my_val = 10.32;

// Datalog (to STDF) the given value using the name of the current test
datalog(my_val); 

// As above, but supply the test name
datalog("MY_TEST_NAME", my_val);

// As above, but also apply any limits and fail the site as required
judgeAndDatalog(my_val); 

// As above, but supply the test name
judgeAndDatalog("MY_TEST_NAME", my_val);
~~~

The above should be used for both parametric and functional tests, where functional tests would have limits set like `1 <= result <= 1` per generally accepted SMT conventions.

### Flow Control

The Origen test program generator can be configured to make all tests appear to pass as described in this comment: https://github.com/Origen-SDK/origen_testers/pull/73#issuecomment-346846082

When `tester.force_pass_on_continue` is set to true, Origen will automatically set `forcePass = 1` on any tests generated with `continue: true`.

It will also automatically set the `onPassFlag` and `onFailFlag` arguments when `tester.force_pass_on_continue` is set and the Origen `if_passed/if_failed` flow control switches have been used.

Note that applying the above arguments is fully built into the `judgeAndDatalog` function, and the user doesn't need to do anything other than set the test method arguments.

### Examples of Creating Custom Tests

Here are a few examples:

A functional test with a data capture and logging:

~~~cpp
#include "origen/test_method/functional_test.hpp"
using namespace Origen;
#include "C402TNVMTester.hpp"


class Read: public Origen::TestMethod::FunctionalTest {

protected:

  // The default functional test body will execute without capture, here we override to add it
  void body()
  {
	origen.capture(32 * 2).pin(NVM_DOUT_PIN).bitPerWord(32).execute();
  }

  // Create some additional tests based on the captured data at the end, the functional test execution
  // will already be monitored and logged for us
  void process(int site) {
    ARRAY_I data = capturedData();

    // Capture this to STDF
    judgeAndDatalog(testName() + "_SB", flip(data[1], 32));
    judgeAndDatalog(testName() + "_MB", flip(data[0], 32));
  }

};
REGISTER_TESTMETHOD("Read", Read);
~~~

A functional test with an overlay:

~~~cpp
#include "origen/test_method/functional_test.hpp"
#include "C402TNVMTester.hpp"

class PgmIfr: public Origen::TestMethod::FunctionalTest {

protected:

  // Overlay the lotID and wafer to all sites in parallel
  void preBody() {
	  
    uint64_t lotid = Origen::site().lotidInt();
    Origen::overlaySubroutine("nvm_lotid1", NVM_DIN_PIN, (uint32_t)(lotid >> 32), 32);
    Origen::overlaySubroutine("nvm_lotid0", NVM_DIN_PIN, (uint32_t)(lotid & 0xFFFFFFFF), 32);
    Origen::overlaySubroutine("nvm_wafer", NVM_DIN_PIN, Origen::site().wafer(), 8);
  }

  // Nothing else is required, let the functional body execute as normal with the overlay in place

};
REGISTER_TESTMETHOD("PgmIfr", PgmIfr);
~~~

### CODE REVIEW

**Comment by ginty** [comment]
@ThaoHuynhFsl, would appreciate your review here too

**Comment by info-rchitect** [comment]
@ginty I remember being this involved with test method libraries on the j973 (C based) so thanks for the walk through memory lane.  My question is whether there will be test interface access to the test method callbacks described above such that users can add test instance specific behaviors without having to fork multiple versions of a similar test method?

**Comment by ginty** [comment]
@info-rchitect, these callbacks are internal to the C++ world and are not intended to form part of an interface to the Origen generation tool.
In short, they are intended to enable users to write their own custom test methods with as small a footprint as possible.
They are very much inspired by the interpose function system on Teradyne and I think they get just about as close to that as you can given the constraints of C++ - i.e. with C++ you can't pass in a function name as an argument and then dynamically call it at runtime.

The test method arguments on the other hand, are the interface to the Origen generation world.

This is the kind of design pattern that is intended to give generation time customization without having to create multiple and very similar test methods...

Let's say a common use case in our test program was to overlay and update a pattern variable before executing the pattern.

To do that, let's create a test method to perform a functional test with the overlay, where the value to be overlaid is a variable and the patterns refer to an overlay variable called "trim_val":

~~~cpp
#include "origen/test_method/functional_test.hpp"

class FuncWithTrimVal: public Origen::TestMethod::FunctionalTest {

    int _trimVal;
    
    void init() {
	addParameter("trimVal",
                     "int",
                     &_trimVal,
                     testmethod::TM_PARAMETER_INPUT)
	  .setComment("The value to be assigned to trim_val before running the test");        
    }

   void preBody() {
      Origen::overlaySubroutine("trim_val", MY_DIN_PIN, _trimVal, 8);
   }

};
REGISTER_TESTMETHOD("FuncWithTrimVal", FuncWithTrimVal);
~~~

That's it, you now have a functional test that supports a trim value overlay without having to write much code at all.

You would then create [an Origen interface definition](http://origen-sdk.org/origen/guides/program/v93k/#Custom_Test_Methods) for that:

~~~ruby
func_with_trim_val:   {
  trim_val:     [:integer, 0],
  # These are the standard arguments that all Origen-enabled test methods have
  test_name:    [:string, ''],
  force_pass:   [:integer, 0],
  on_pass_flag: [:string, ''],
  on_fail_flag: [:string, '']
},
~~~

and an interface handler that will choose this test method when appropriate:

~~~ruby
def func(name, options={})
  # ...
  if options[:trim_val]
    t.test_method = test_methods.my_lib.func_with_trim_val(options)
  else
    t.test_method = test_methods.origen.functional_test(options)
  end
  # ...
end
~~~

Then you can overlay at will within your flow:

~~~ruby
func :pattern_a

func :pattern_a, trim_val: 5, id: :pa5

func :pattern_a, trim_val: 6, if_failed: :pa5
~~~

You can hopefully imagine further variations on this to make the overlay variable name a parameter and so on.

**Comment by ginty** [comment]
All reviewers - this has been sitting for a long time and works well in my application.
I need to build more stuff on top and the time has come to merge or object.

**Unless I hear otherwise, I am going to go ahead and merge this on the 2nd May - two days from now.**

**Review by coreyeng — APPROVED** [review]

**Pull request merged**
